canonifyURLs = true

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "vuthehuyvnu@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  
[Languages]
[Languages.en]
title = "Capture Data Change from RDS to AWS OpenSearch"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - FB Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Author's Linkedin"
identifier = "Linkedin"
url = "https://www.linkedin.com/in/vuthehuyht"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Author's GitHub"
identifier = "GitHub"
url = "https://github.com/vuthehuyht"
weight = 20

[Languages.vi]
title = "Thu thập dữ liệu thay đổi từ RDS tới OpenSearch"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm FB"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-linkedin'></i> Author's Linkedin"
identifier = "Linkedin"
url = "https://www.linkedin.com/in/vuthehuyht"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Author's GitHub"
identifier = "GitHub"
url = "https://github.com/vuthehuyht"
weight = 20
